import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/navbar/Header'
import Footer from '@/components/footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Liquid Maestro',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='container'>
          {children}
        </div>
      </body>
    </html>
  )
}
